import { District} from './District.enum';

export const DistrictLabel: Record<District, string> = {
  [District.ANCON]: 'Ancón',
  [District.ASIA]: 'Asia',
  [District.ATE]: 'Ate',
  [District.BARRANCO]: 'Barranco',
  [District.BRENA]: 'Breña',
  [District.CARABAYLLO]: 'Carabayllo',
  [District.CHACLACAYO]: 'Chaclacayo',
  [District.CERCADO]: 'Cercado de Lima',
  [District.CHORRILLOS]: 'Chorrillos',
  [District.CIENEGUILLA]: 'Cieneguilla',
  [District.COMAS]: 'Comas',
  [District.EL_AGUSTINO]: 'El Agustino',
  [District.INDEPENDENCIA]: 'Independencia',
  [District.JESUS_MARIA]: 'Jesús María',
  [District.LA_MOLINA]: 'La Molina',
  [District.LA_VICTORIA]: 'La Victoria',
  [District.LURIGANCHO]: 'Lurigancho',
  [District.LURIN]: 'Lurín',
  [District.MAGDALENA_DEL_MAR]: 'Magdalena del Mar',
  [District.MIRAFLORES]: 'Miraflores',
  [District.PACHACAMAC]: 'Pachacamac',
  [District.PUCUSANA]: 'Pucusana',
  [District.PUEBLO_LIBRE]: 'Pueblo Libre',
  [District.PUENTE_PIEDRA]: 'Puente Piedra',
  [District.PUNTA_HERMOSA]: 'Punta Hermosa',
  [District.PUNTA_NEGRA]: 'Punta Negra',
  [District.RIMAC]: 'Rímac',
  [District.SAN_BARTOLO]: 'San Bartolo',
  [District.SAN_BORJA]: 'San Borja',
  [District.SAN_ISIDRO]: 'San Isidro',
  [District.SAN_JUAN_DE_LURIGANCHO]: 'San Juan de Lurigancho',
  [District.SAN_JUAN_DE_MIRAFLORES]: 'San Juan de Miraflores',
  [District.SAN_LUIS]: 'San Luis',
  [District.SAN_MARTIN_DE_PORRES]: 'San Martín de Porres',
  [District.SAN_MIGUEL]: 'San Miguel',
  [District.SANTA_ANITA]: 'Santa Anita',
  [District.SANTA_MARIA_DEL_MAR]: 'Santa María del Mar',
  [District.SANTA_ROSA]: 'Santa Rosa',
  [District.SANTIAGO_DE_SURCO]: 'Santiago de Surco',
  [District.SURQUILLO]: 'Surquillo',
  [District.VILLA_EL_SALVADOR]: 'Villa El Salvador',
  [District.VILLA_MARIA_DEL_TRIUNFO]: 'Villa María del Triunfo'
};
